[project]
name = "python-expert"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.ruff.lint]
select = ["E", "F"]
ignore = [
    "E501",   # líneas largas
    "I001",   # imports sin ordenar
    "DTZ003", # datetime.now() sin timezone
]
